### ISSUE TITLE
I want to add lunarVim to the install process and I don't know if I'm doing it right?

### ISSUE THREAD

**Issue by marcograhl** [axonasif/dotfiles-sh#10]
Hi Axon,

I saw your Talk and it got me excited to play around with gitpod and ssh. I tried to add lunarVim to the installation and I don't know if I'm doing it correctly?

Here is your forked repo, with the modifications:
https://github.com/marcograhl/dotfiles-sh-test

Right now I just install it every time. Thanks for showing how to set this all up - much appreciated

kind regards marco

**Comment by axonasif** [comment]
Hi @marcograhl

If you run the command in the following manner, it should work

https://github.com/axonasif/dotfiles-sh/blob/5cd761f52d67f9fb940210f432eb9b04066cf630/src/install/neovim.sh#L13

Instead of this command [here](https://github.com/marcograhl/dotfiles-sh-test/blob/2ba24206d28c326727c0112442a42f79dfa24813/src/install/lunarVim.sh#L3) on your fork. Basically, `curl` can't execute the script for you, you have to pipe it to `bash`.

As a side note, I also replaced NvChad with LunarVim as it looks like LunarVim creates a wrapper script and does not put itself as the default config for neovim, which is probably good for putting as an example ready-to-use config :)
So that means, if you pull the new changes from here to your fork, it should just work!

**Comment by marcograhl** [comment]
Thats awesome, I didn't know we need to pupe it to bash. I'm very new to this.

Awesome that you added LunarVim, I will test this out. Thank you Axon  🙌

How would I add a custom config.lua to the mix?

**Comment by marcograhl** [comment]
I tested it and It works like a charm, thanks
